### PR TITLE
Update react15

### PR DESCRIPTION
**Pull request by LarsMq73**
Hi,
here my forked branch with the update to React 15 incl. all node modules updates (done with ncu - node-check-updates)

please check it.
as discussed you will adjust the liniting config, 

thanks for all! 
Lars

### CODE REVIEW

**Comment by LarsMq73** [comment]
Hi, it just came into my mind: I did not update the version number in the package.json, it is still 3.0.0 - I think it schuld be a new One...?

**Comment by patw0929** [comment]
Sorry, I'm still working it.
I fail the tests every time... try to fix now.

**Comment by adamtrilling** [comment]
@patw0929 I've been working on this for a day or so...the tests fail because each call to ReactDom.render() appears to take longer than the last one. It's very weird. I have been digging into the React source code to see if I can find what's taking so long, but not making a lot of progress.

**Comment by LarsMq73** [comment]
Hi,
thank you very much, it works fine for me.
Lars

**Pull request merged**
