### PR TITLE
Removed libphonenumber.js

### PR DESCRIPTION
**Pull request by patw0929**
As #242 & #245, we don't need libphonenumber.js in this repo.
In future, please maintain libphonenumber.js at this [repo](https://github.com/patw0929/libphonenumber-js-utils).

### CODE REVIEW

**Comment by patw0929** [comment]
This pull request **introduces 2 alerts** and **fixes 2** when merging 8903e7d149b6b37cfc0590a071b71eefbac19afc into 3b70c5d9d85cc333e3c604e9cb123622c14df24c - [view on LGTM.com](https://lgtm.com/projects/g/patw0929/react-intl-tel-input/rev/pr-0c2bfb8f26f2acc002e57f6bb89ab36228fd691b)

**new alerts:**

* 2 for Unused variable, import, function or class

**fixed alerts:**

* 2 for Unneeded defensive code

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by nutboltu** [comment]
Lets add the [webpack-bundle-analyzer](https://www.npmjs.com/package/webpack-bundle-analyzer) and compare the bundle size

**Comment by patw0929** [comment]
This pull request **fixes 2 alerts** when merging 35cce22f04b5e9cc7223bfb2a9e5ba4d55d3d7b3 into 3b70c5d9d85cc333e3c604e9cb123622c14df24c - [view on LGTM.com](https://lgtm.com/projects/g/patw0929/react-intl-tel-input/rev/pr-14548c3d7f61e44481f126df0eff0d193c79260d)

**fixed alerts:**

* 2 for Unneeded defensive code

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by patw0929** [comment]
> Lets add the [webpack-bundle-analyzer](https://www.npmjs.com/package/webpack-bundle-analyzer) and compare the bundle size

Good point. I'll add it in another PR.

**Pull request merged**
