### PR TITLE
[Update] npmignore updated with file list

### LINKED ISSUE #231: [Bundle improvement] - Update .npmignore
Thanks for this library! Really cool implementation of `intl-tel-input` 😄

### The Issue

At the moment the bundled package contains the entire source code because the `.npmignore` is empty.

Would it be possible to add files which are non-essential for library consumers to the `.npmignore`? 
Some example files to exclude (there are more):
```
yarn.lock
.editorconfig
src/
example/
```

I am happy to do this work, or feel free to close this issue if the entire source is bundled for a reason 👍

### PR DESCRIPTION
**Pull request by nutboltu**
Fixes #231

### CODE REVIEW

**Comment by superhit0** [comment]
```
# ignore all

*

# override above and include only dist folder

!dist/**/*
```

@nutboltu @patw0929 

How about this approach?

to me it looks cleaner

**Comment by nutboltu** [comment]
@superhit0 shouldn't we include `LICENSE`, `package.json`, `CHANGELOG.md` etc. to give the user more context about the library?

**Comment by superhit0** [comment]
LGTM from me.

@patw0929 can you confirm on this ?

**Comment by patw0929** [comment]
According to [npmjs doc](https://docs.npmjs.com/misc/developers#keeping-files-out-of-your-package):

> The following paths and files are never ignored, so adding them to .npmignore is pointless:
> 
> package.json
> README (and its variants)
> CHANGELOG (and its variants)
> LICENSE / LICENCE

Can you help to confirm it? Thanks!

**Comment by nutboltu** [comment]
@patw0929 Thanks for the feedback. I didn't know that `.npmignore` never ignore these files. I updated the PR.

**Pull request merged**
