### PR TITLE
fix: highlight country from preferred list

### PR DESCRIPTION
**Pull request by denis-k**
When we define a `preferredCountries` property, we have a list of the preferred countries on the top of the drop-down menu. But when we open a drop-down, the selected country by default will be in general list, not in a `preferredCountries` list. See a demo:
Alt text

In this case, `preferredCountries` is hidden from the user. He will not expect to find it and will not look for it.

Instead, let's try to select a country from the `preferredCountries` list. See a demo:
Alt text

### CODE REVIEW

**Comment by denis-k** [comment]
I would like to add a unit test, but I have an error:
`Cannot find module 'react' from 'RootModal.test.js'`
Alt text

@patw0929, Do you know what can be a problem?

**Comment by patw0929** [comment]
Awesome! Thank you 👍 

The missing module error of react when running test, please install peer dependency packages by following command:

```bash
yarn add react@^15.4.2 react-dom@^15.4.2 prop-types@~15.5.8 --peer
```

**Comment by denis-k** [comment]
@patw0929 it works, thanks. I will add a test.

**Comment by denis-k** [comment]
I added a small test, @patw0929 could you pls take a look? ;)

**Comment by patw0929** [comment]
LGTM 💯 
Thank you for your contribution! Will merge later.

**Pull request merged**
