### PR TITLE
Added fix for Issue 253 & Updated libphonenumber to 8.10.2

### PR DESCRIPTION
**Pull request by superhit0**
* Suggested Fix for - https://github.com/patw0929/react-intl-tel-input/issues/253
* Update `libphonenumber-js-utils` to `8.10.2`
* Updated package-lock.json -- `npm start would be fixed as well`.

### CODE REVIEW

**Comment by superhit0** [comment]
@patw0929 can you upgrade the version of `libphonenumber` to `8.10.2`

Then I will push `yarn.lock` & `package-lock` as well.

**Comment by patw0929** [comment]
I still meet the issue of #253 (`window is not defined`) with this PR.

**Comment by patw0929** [comment]
Oh, by the way, I had already published `libphonenumber-js-utils` to v8.10.2.

**Comment by patw0929** [comment]
It works!

### Screenshot:


### `next.config.js`
```js
const withCSS = require('@zeit/next-css');

module.exports = withCSS({
  webpack: function (config) {
    config.module.rules.push({
      test: /\.(png|jpg|gif)$/,
      use: {
        loader: 'file-loader',
        options: {
          publicPath: '../../static/',
          outputPath: './static/',
        },
      }
    })
    return config
  }
});

```

### `attempt-to-import.js`
```js
import { Fragment } from 'react';
import IntlTelInput from 'react-intl-tel-input';
import style from 'react-intl-tel-input/dist/main.css';

export default () => (
  <Fragment>
    <style dangerouslySetInnerHTML={{ __html: style }} />
    <IntlTelInput />
  </Fragment>
);

```

**Comment by patw0929** [comment]
@superhit0 Could you update yarn.lock?
Thanks!

**Comment by superhit0** [comment]
@patw0929 updated yarn.lock

**Pull request merged**
