### PR TITLE
Update IntlTelInputApp to allow controlled value from outside

### PR DESCRIPTION
**Pull request by chris-verclytte**
Solves #165. Breaks current API contract.

### CODE REVIEW

**Comment by patw0929** [comment]
Cool! Thanks a lot! I'll handle this PR at tomorrow night.

**Comment by patw0929** [comment]
Sorry for the late reply, could you help to update the demo page (`index.html`) about the props  `value` & `defaultValue`? Like when should we use the `value`/`defaultValue`.

Thanks for the help again. 🙏

**Comment by chris-verclytte** [comment]
Does this make the props sufficiently clear ?

**Comment by Zephir77167** [comment]
Hi, I'm not sure but I think this has introduced a bug in this lib.

I'm using it with the new prop `initialValue`, but it doesn't show in the input and doesn't fire the `onPhoneNumberChange` method.

**Comment by chris-verclytte** [comment]
Indeed, I think removing of [componentDidUpdate hook](https://github.com/patw0929/react-intl-tel-input/pull/166/files#diff-8d03d40cef8605ae4608d7284524a5b7L246https://github.com/patw0929/react-intl-tel-input/pull/166/files#diff-8d03d40cef8605ae4608d7284524a5b7L246) is responsible for this. Can't remember why I got rid of this one.

**Comment by Zephir77167** [comment]
It's because a controlled component doesn't need to be notified of updates I guess (because IT handles the updates). I opened a PR to fix this: https://github.com/patw0929/react-intl-tel-input/pull/171

**Comment by chris-verclytte** [comment]
Hmmm, controlled component also need notifyPhoneNumberChange and I also encountered the problem of it not being triggered at the initialization then you should be right, as soon as I get some time, I will try to look at it deeper.

**Comment by Zephir77167** [comment]
I see... I won't update until this is fixed as it is quite breaking in my case. Notify me if you want some help!

**Comment by Zephir77167** [comment]
My PR has been merged and the problem in my case (initialValue) is resolved. Doesn't solve it for controlled components (value) though, and I haven't had the time to take a look

**Comment by chris-verclytte** [comment]
Yes that's what I have seen, I am going to investigate it asap !

**Pull request merged**
