### PR TITLE
Removed the dependency of Sass

### PR DESCRIPTION
**Pull request by patw0929**
Related issue: https://github.com/patw0929/react-intl-tel-input/issues/62

### CODE REVIEW

**Comment by brunops** [comment]
Dude, that looks promising! Thanks for taking the time :)

I'm having trouble with the flags `.png` resolution on the main App now.

These are the steps I'm using to test it:
I've pulled this `feature/t62` branch and ran (by the way, you shouldn't have to commit your `dist/` folder files at all, I can try to configure it later)
```sh
grunt build:dist && cp dist/main.js dist/main.css ../my-app/node_modules/react-intl-tel-input/dist/
```

But when running webpack in my main app I get:
```
ERROR in ./~/css-loader!./~/react-intl-tel-input/dist/main.css
Module not found: Error: Cannot resolve 'file' or 'directory' ./flags.png in /Users/brunops/my-app/node_modules/react-intl-tel-input/dist
 @ ./~/css-loader!./~/react-intl-tel-input/dist/main.css 6:17174-17196

ERROR in ./~/css-loader!./~/react-intl-tel-input/dist/main.css
Module not found: Error: Cannot resolve 'file' or 'directory' ./flags@2x.png in /Users/brunops/my-app/node_modules/react-intl-tel-input/dist
 @ ./~/css-loader!./~/react-intl-tel-input/dist/main.css 6:17593-17618
```

This is the current loaders I have in my webpack config (tried to copy from yours):

```js
            {
                test: /\.css/,
                loader: 'style!css'
            },
            {
                test: /\.png$/i,
                loaders: [
                    'file?hash=sha512&digest=hex&name=[name].[ext]',
                    'image-webpack?{progressive:true, optimizationLevel: 3, interlaced: false, pngquant:{quality: "30-40", speed: 1}}'
                ]
            }
```

I'll keep debugging, let me know if you have any clues

**Comment by brunops** [comment]
Worked :+1:

**Comment by patw0929** [comment]
> PS: You shouldn't have to commit your dist/ folder files at all, I can try to configure it if you want

I don't get it. If I don't commit `dist/` files, how people can import this package?

**Comment by brunops** [comment]
By adding a `"prepublish"` task in your `package.json`, which means it gets published, but not tracked on git. No need for it in this PR though, I can send one configuring it on top of this changes once its merged if you want.

**Comment by patw0929** [comment]
Merged this PR. 
@brunops: Could you help to implement the `prepublish` function? Thank you! :)

**Comment by brunops** [comment]
@patw0929 Sure! When do you plan to publish this new changes?

**Comment by patw0929** [comment]
@brunops: 
Sorry for the late reply. Merged #65 & #66 and published as v2.0.11. Thanks a lot! :+1:

**Pull request merged**
