### PR TITLE
Fix cursor Issue#205

### PR DESCRIPTION
**Pull request by superhit0**
Fixing Cursor [Issue#205](https://github.com/patw0929/react-intl-tel-input/issues/205)

@patw0929

### CODE REVIEW

**Comment by patw0929** [comment]
Thanks!
But I met some weird cases:

1. At demo page, select Taiwan first, and enter word by word: 0912345678. The cursor will not after the `8` after enter the `8`.
2. At demo page too. Select Taiwan, and enter word by word: +886912345678. The `+` plus sign will at the end of string.

**Comment by superhit0** [comment]
Yeah, thanks for pointing it out. Will revamp the algorithm.

**Comment by patw0929** [comment]
Looks good to me! 👍

**Comment by superhit0** [comment]
@patw0929 Can we merge it?

**Comment by patw0929** [comment]
Oh sorry, I found another weird case: 😢 

image

When I press backspace at the end of an us phone number, it will left some part.

**Comment by superhit0** [comment]
@patw0929 Can you please check now?

**Comment by patw0929** [comment]
@superhit0 Looks great! Thanks!

**Comment by superhit0** [comment]
@patw0929 If its ok, Can we merge it?
Or should we do more tests?

**Comment by patw0929** [comment]
Yes, we can merge it first.

**Pull request merged**
