### PR TITLE
Multiple components without IDs

### PR DESCRIPTION
**Pull request by janmarek**
It's based on your branch `revert-dispatch-id` which already worked. I have removed remains of id property from components, documentation and tests. I recommend you to run the tests because I can't (#83).

### CODE REVIEW

**Comment by patw0929** [comment]
@janmarek Thanks! :+1: 
But when I type in the first phone input, the number is displayed in the second input's result area.
Is there any good solution to solve this?

**Comment by janmarek** [comment]
I'll take a look into this. Do you have any other problems with it?

**Comment by patw0929** [comment]
Nope. Seems perfect without that issue for me. :+1:

**Comment by janmarek** [comment]
Example is fixed.

**Pull request merged**
